-- MySQL Workbench Synchronization
-- Generated: 2019-02-14 20:32
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Brady Berner

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE TABLE IF NOT EXISTS `laravelCLC`.`EDUCATION` (
  `IDEDUCATION` INT(11) NOT NULL AUTO_INCREMENT,
  `DEGREE` VARCHAR(45) NOT NULL,
  `FIELD` VARCHAR(45) NOT NULL,
  `GPA` FLOAT(11) NOT NULL,
  `STARTYEAR` INT(11) NOT NULL,
  `ENDYEAR` INT(11) NOT NULL,
  `USERS_IDUSERS` INT(11) NOT NULL,
  PRIMARY KEY (`IDEDUCATION`),
  INDEX `fk_EDUCATION_USERS1_idx` (`USERS_IDUSERS` ASC),
  CONSTRAINT `fk_EDUCATION_USERS1`
    FOREIGN KEY (`USERS_IDUSERS`)
    REFERENCES `laravelCLC`.`USERS` (`IDUSERS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `laravelCLC`.`EXPERIENCE` (
  `IDEXPERIENCE` INT(11) NOT NULL AUTO_INCREMENT,
  `TITLE` VARCHAR(45) NOT NULL,
  `COMPANY` VARCHAR(45) NOT NULL,
  `CURRENT` VARCHAR(45) NOT NULL,
  `STARTYEAR` VARCHAR(45) NOT NULL,
  `ENDYEAR` VARCHAR(45) NULL DEFAULT NULL,
  `DESCRIPTION` VARCHAR(45) NULL DEFAULT NULL,
  `USERS_IDUSERS` INT(11) NOT NULL,
  PRIMARY KEY (`IDEXPERIENCE`),
  INDEX `fk_EXPERIENCE_USERS1_idx` (`USERS_IDUSERS` ASC),
  CONSTRAINT `fk_EXPERIENCE_USERS1`
    FOREIGN KEY (`USERS_IDUSERS`)
    REFERENCES `laravelCLC`.`USERS` (`IDUSERS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `laravelCLC`.`JOBS` (
  `IDJOBS` INT(11) NOT NULL AUTO_INCREMENT,
  `TITLE` VARCHAR(45) NOT NULL,
  `COMPANY` VARCHAR(45) NOT NULL,
  `STATE` VARCHAR(45) NOT NULL,
  `CITY` VARCHAR(45) NOT NULL,
  `DESCRIPTION` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDJOBS`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
